/**
* Heracles
* Heracles money formatting
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.pleo.heracles.infrastructure.api.formatamount.v1

import io.pleo.heracles.infrastructure.api.common.dto.v1.Amount
import io.pleo.heracles.infrastructure.api.common.dto.v1.Header

import com.squareup.moshi.Json
/**
 * 
 * @param header 
 * @param amount 
 */
data class FormatAmountRequest (
    @Json(name = "header")
    val header: io.pleo.heracles.infrastructure.api.common.dto.v1.Header,
    @Json(name = "amount")
    val amount: io.pleo.heracles.infrastructure.api.common.dto.v1.Amount
) {

}

